#!/bin/bash
HOST="192.168.1.7"
REMOTE_USER="pi"
REMOTE_REPO_PATH="/home/pi/project/pi-water-monitor"
LOCAL_REPO_PATH="/Users/Flux/ANU/COMP3710/pi-water-monitor"
UPDATE_COMMAND="PATH=$PATH:/home/pi/.local/bin/ bash $REMOTE_REPO_PATH/reporter/run.sh"

scp -r "$LOCAL_REPO_PATH/reporter" $REMOTE_USER@$HOST:$REMOTE_REPO_PATH
ssh -t $REMOTE_USER@$HOST "$UPDATE_COMMAND"
